name: release
on: pull_request
jobs:
  goreleaser:
    name: Generate TOC
    runs-on: ubuntu-latest
      - name: Generate README index
        uses: technote-space/toc-generator@v3
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN  }}
